### PR TITLE
#338 - branch dan-fix-versions-upgrade - Fixed Provider bugs, TF upgrade. from v1.0.10 to v1.6.0

### PR DESCRIPTION
**Pull request by danishkamili**
Fixed Provider Bug for effective labels 
[https://github.com/hashicorp/terraform-provider-google/issues/16217]

Upgraded Terraform version - removed dependency on optional experimental features 
[[https://developer.hashicorp.com/terraform/language/v1.3.x/upgrade-guides#concluding-the-optional-attributes-experiment]()]

Currently Tested and live in lab at - 
terraform version
Terraform v1.6.0
on linux_amd64

Provider: >=3.50

Since, terraform version upgrade requires all the dependent files like root or child modules to be compatible, hence, doing small chunks for fixing provider bugs or upgrades didn't seem feasible, hence, a single PR for the both.

Modules touched mainly:

Cloudbuild
audit-bunker
landing-zone-bootstrap
logging-center
22-private-service-connect
All the 
variable.tf  which included experimental features
terraform.tf which had downgraded version as well optional feature 

let me know if more information is needed or the testing on your end yields a different results or issues.

### CODE REVIEW

**Comment by danishkamili** [comment]
build-results

**Comment by danishkamili** [comment]
build-results-1

**Comment by danishkamili** [comment]
@obriensystems  let me know if you want me to add more information to the PR, or test screen shots or results.

**Comment by fmichaelobrien** [comment]
The pr looks good.
I would merge as long as you have tested all 4 triggers (boot, common, nprod, prod) ideally in a new organization

**Review by fmichaelobrien — APPROVED** [review]
/lgtm
I didn't do my own deploy of the pr - will queue it later

**Comment by danishkamili** [comment]
@obriensystems tested all 4 triggers in an org with no existing LZ deployed, although it previously had LZ deployed, but everything was cleaned up prior to this test, should be ok, imo.

**Comment by fmichaelobrien** [comment]
Very nice.

Let me know if you don't see the merge button - but I think you do.

**Pull request merged**
